language: python
python: 3.7

install:
  - pip install pipenv
  - pipenv install pipenv_to_requirements

script: echo skipping tests

before_deploy: pipenv run pipenv_to_requirements -f

deploy:
  provider: azure_web_apps
  on: master
  skip_cleanup: true
  verbose: true
