# Generated by Django 2.2.3 on 2019-07-27 01:45

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(editable=False, max_length=200, unique=True)),
                ('original_url', models.URLField(editable=False, unique=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
