# Generated by Django 2.2.3 on 2019-08-01 18:39

from django.db import migrations, models
import django.utils.timezone
import word_service.service


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('giggle', models.CharField(default=word_service.service.get_next_giggle, max_length=72, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
