# Generated by Django 2.2.3 on 2019-07-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190727_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='id',
        ),
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.URLField(editable=False),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(editable=False, max_length=200, primary_key=True, serialize=False),
        ),
    ]
