"""
Django settings for giggleurl project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

PY_ENV = os.getenv("PY_ENV", "development")

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SECRET_KEY = os.getenv("SECRET_KEY", "dev_secret_key")

DEBUG = PY_ENV != "production"

# Required for Azure deployment
ALLOWED_HOSTS = (
    [os.environ["WEBSITE_SITE_NAME"] + ".azurewebsites.net", "127.0.0.1"]
    if "WEBSITE_SITE_NAME" in os.environ
    else ["localhost"]
)

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "rest_framework",
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "giggleurl.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

WSGI_APPLICATION = "giggleurl.wsgi.application"


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": os.getenv("DB_NAME", "giggleurl"),
        "USER": os.getenv("DB_USER", "dev"),
        "PASSWORD": os.getenv("DB_PASSWORD", "devpassword"),
        "HOST": os.getenv("DB_HOSTNAME", "localhost"),
        "PORT": os.getenv("DB_PORT", 5432),
    }
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {"require_debug_false": {"()": "django.utils.log.RequireDebugFalse"}},
    "handlers": {
        "logfile": {
            "class": "logging.handlers.WatchedFileHandler",
            "filename": (
                "/home/LogFiles/app.log" if PY_ENV == "production" else "app.log"
            ),
        }
    },
    "loggers": {
        "django": {
            "handlers": ["logfile"],
            "level": os.getenv("LOG_LEVEL", "INFO"),
            "propagate": False,
        }
    },
}


AUTH_PASSWORD_VALIDATORS = []

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = False
USE_L10N = False
USE_TZ = True
